const app=document.querySelector('#app');
const db=window.ARCHIVE_DATA;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const artist=id=>db.artists.find(a=>a.id===id);
const work=id=>db.artworks.find(w=>w.id===id);
const img=(src,alt,cls='')=>src?`<img class="${cls}" src="${esc(src)}" alt="${esc(alt)}">`:`<div class="missing ${cls}">Image pending</div>`;

function active(name){document.querySelectorAll('.nav nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===name))}
function shell(content,page=''){active(page);app.innerHTML=content;scrollTo(0,0)}
function footer(){return `<section class="quote"><button aria-label="Return to top">○</button><em>“Art is the echo of time, and the archive is how we listen.”</em><span>Discover　────────</span></section>`}
function rail(){return `<aside class="sideRail"><div class="language">中 / <u>EN</u></div><button class="menu">☰</button><div class="railArch"></div></aside>`}
function crumb(items){return `<div class="crumb">HOME　›　${items.map(x=>esc(x)).join('　›　')}</div>`}
function workCard(w){const a=artist(w.artistId);return `<a class="workCard" href="#work/${w.id}">${img(w.imageAsset,w.title)}<h3>${esc(w.title)}</h3><p>${esc(a.name)} · ${esc(w.yearDisplay||'Date unknown')}</p><small>${esc(a.movement)}　·　${esc(w.medium)}</small></a>`}

function home(){const picks=[db.artists[8],db.artworks.find(w=>w.artistId==='A009'),db.artworks.find(w=>w.artistId==='A007')];shell(`<section class="homeHero"><div class="heroImage" id="heroImage"></div><div class="heroWords"><h1>Reframing<br>Fine Art<br>Digitally</h1><p>A bilingual digital platform exploring fine art through artist archives, artworks, and cultural narratives.</p><a class="textLink" href="#artists">Explore archive　⟶</a></div><div class="scrollMark">SCROLL　●　│</div>${rail()}</section><section class="portalCards"><a href="#artists"><div class="portalImage">${img(picks[0].portraitAsset,picks[0].name)}</div><span>01</span><h2>Artists</h2><p>Discover artists across eras, regions, and movements.</p><b>View all artists　⟶</b></a><a href="#works"><div class="portalImage">${img(picks[1].imageAsset,picks[1].title)}</div><span>02</span><h2>Works</h2><p>Explore artworks with detailed information and high-resolution images.</p><b>Browse works　⟶</b></a><a href="#about"><div class="portalImage">${img(picks[2].imageAsset,picks[2].title)}</div><span>03</span><h2>Archive</h2><p>Access timelines, collections, and historical materials.</p><b>Enter archive　⟶</b></a></section>${footer()}`,'home');bindHero()}

function artists(){const movements=[...new Set(db.artists.map(a=>a.movement))];shell(`<section class="museumBanner"><div>${crumb(['ARTISTS'])}<span class="kicker">Artist archive</span><h1>Discover Artists<br>Across Eras</h1><p>Explore the lives, practices, and legacies of artists across cultures, movements, and generations.</p><a class="textLink" href="#about">About the archive　⟶</a></div>${rail()}</section><section class="catalog artistsCatalog"><div class="catalogMain"><div class="catalogTop"><b>ALL ARTISTS　·　${db.artists.length}</b><span>VIEW AS　▦　☰</span></div><div class="artistGrid" id="artistGrid">${db.artists.map(artistCard).join('')}</div></div><aside class="filterPanel"><label><input id="artistSearch" placeholder="Search artists..."><span>⌕</span></label><h4>Filter by</h4><small>Movement</small><select id="movementFilter"><option value="">All movements</option>${movements.map(m=>`<option>${esc(m)}</option>`).join('')}</select><small>Nationality</small><select id="nationFilter"><option value="">All regions</option>${[...new Set(db.artists.map(a=>a.nationality))].map(n=>`<option>${esc(n)}</option>`).join('')}</select><small>Medium</small><select><option>All mediums</option></select><button id="resetArtists">Reset filters　⟶</button></aside></section>${footer()}`,'artists');bindArtistFilters()}
function artistCard(a){return `<a class="artistCard" href="#artist/${a.id}">${img(a.portraitAsset,a.name)}<h2>${esc(a.name)}</h2><p>${a.birthYear}—${a.deathYear}</p><small>${esc(a.movement)}</small><p class="summary">${esc(a.nationality)} artist working across ${esc(a.mediums.join(', '))}.</p><b>View profile　⟶</b></a>`}

function artistDetail(id){const a=artist(id)||db.artists[0],works=db.artworks.filter(w=>w.artistId===a.id);shell(`<section class="artistProfile">${crumb(['ARTISTS',a.name])}<div class="profileIntro"><div><h1>${esc(a.name)}</h1><h2>${esc(a.nameZh)}</h2><h3>${a.birthYear} – ${a.deathYear}</h3><p>${esc(a.movement)}</p><p class="summary">${esc(a.name)} was a ${esc(a.nationality.toLowerCase())} artist whose archive includes ${works.length} works spanning ${esc(a.mediums.join(', '))}.</p><a class="textLink" href="#timeline">View timeline　⟶</a></div>${img(a.portraitAsset,a.name,'profilePortrait')}<dl><div><dt>Birth / Death</dt><dd>${a.birthYear} – ${a.deathYear}</dd></div><div><dt>Nationality</dt><dd>${esc(a.nationality)}</dd></div><div><dt>Field</dt><dd>${esc(a.mediums.join(', '))}</dd></div><div><dt>Style / Movement</dt><dd>${esc(a.movement)}</dd></div><div><dt>Works in archive</dt><dd>${works.length}</dd></div><div><dt>Copyright</dt><dd>${esc(a.copyrightStatus)}</dd></div></dl></div></section><section class="profileWorks"><div class="biography"><h4>BIOGRAPHY</h4><p>${esc(a.name)} (${a.birthYear}–${a.deathYear}) is represented in this digital archive through works, exhibition records, and a biographical timeline.</p><p>The available metadata situates the artist within ${esc(a.movement)} and documents a practice centred on ${esc(a.mediums.join(', '))}.</p></div><div><div class="rowTitle"><h4>SELECTED WORKS</h4><a href="#works">View all works　⟶</a></div><div class="selectedWorks">${works.slice(0,5).map(workCard).join('')}</div></div></section><section class="timelineStrip" id="timeline"><h4>TIMELINE</h4>${a.timeline.map(t=>`<div><b>${t.year}</b><i></i><p>${esc(t.label)}</p></div>`).join('')}</section>${footer()}`,'artists')}

function works(){const movements=[...new Set(db.artists.map(a=>a.movement))];shell(`<section class="museumBanner worksBanner"><div>${crumb(['WORKS'])}<h1>Works</h1><p>Explore artworks from the seventeenth century to modern movements. Discover the archive through time, mediums, and artistic expression.</p><a class="textLink" href="#about">About the archive　⟶</a></div>${rail()}</section><section class="workFilters"><b>FILTER BY</b><label>ARTIST<select id="workArtist"><option value="">All artists</option>${db.artists.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label>MOVEMENT<select id="workMovement"><option value="">All movements</option>${movements.map(m=>`<option>${esc(m)}</option>`).join('')}</select></label><label>MEDIUM<select><option>All mediums</option></select></label><label>SORT BY<select id="workSort"><option value="latest">Latest</option><option value="earliest">Earliest</option></select></label><label class="search"><input id="workSearch" placeholder="Search works..."><span>⌕</span></label></section><section class="worksCatalog"><div class="catalogTop"><b>ALL WORKS　·　<span id="workCount">${db.artworks.length}</span></b><span>VIEW AS　▦　☰</span></div><div class="worksGrid" id="worksGrid">${db.artworks.map(workCard).join('')}</div></section>${footer()}`,'works');bindWorkFilters()}

function workDetail(id){const w=work(id)||db.artworks[0],a=artist(w.artistId),related=db.artworks.filter(x=>x.artistId===a.id&&x.id!==w.id).slice(0,3);shell(`<section class="workDetail">${crumb(['WORKS',w.title])}<div class="workDetailGrid"><div><div class="mainArtwork">${img(w.imageAsset,w.title)}</div><div class="imageControls"><span>⌗　VIEW FULL SCREEN</span><span>←　 01 / 01　 →</span></div></div><div class="workInfo"><h1>${esc(w.title)}</h1><h2>${esc(a.nameZh)}</h2><a href="#artist/${a.id}">${esc(a.name)}</a><dl><div><dt>Artist</dt><dd>${esc(a.name)}　${esc(a.nameZh)}</dd></div><div><dt>Movement</dt><dd>${esc(a.movement)}</dd></div><div><dt>Date</dt><dd>${esc(w.yearDisplay||'Date unknown')}</dd></div><div><dt>Medium</dt><dd>${esc(w.medium)}</dd></div><div><dt>Collection</dt><dd>${esc(w.collection)}</dd></div><div><dt>Copyright</dt><dd>${esc(w.copyrightStatus)}</dd></div></dl><b class="share">SHARE　　♧　f　♥　↗</b></div>${rail()}</div></section><section class="workBelow"><div><h4>ABOUT THE WORK</h4><p>${esc(w.title)} is catalogued in The Art Archive as part of ${esc(a.name)}’s body of work. The record preserves its known date, medium, collection, source, and rights information.</p><p>Some fields remain under scholarly review and will be updated as the archive develops.</p><a class="textLink" href="#about">Read more　⟶</a></div><div class="details"><h4>DETAILS</h4><dl><div><dt>Artist ID</dt><dd>${esc(a.id)}</dd></div><div><dt>Artwork ID</dt><dd>${esc(w.id)}</dd></div><div><dt>Status</dt><dd>${esc(w.verificationStatus)}</dd></div><div><dt>Source</dt><dd>${esc(w.source)}</dd></div></dl></div><div><div class="rowTitle"><h4>RELATED WORKS</h4><a href="#works">View all works　⟶</a></div><div class="relatedWorks">${related.map(workCard).join('')}</div></div></section>${footer()}`,'works')}

function about(){shell(`<section class="museumBanner aboutBanner"><div>${crumb(['ABOUT'])}<h1>About the<br>Archive</h1><p>The Art Archive is a bilingual research-led platform bringing together artist biographies, artworks, and cultural timelines.</p></div>${rail()}</section><section class="aboutBody"><h2>10 artists.<br>87 artworks.<br>One evolving archive.</h2><div><p>This prototype transforms the supplied metadata into an accessible visual collection. It keeps incomplete or unverified records visible without inventing missing scholarship.</p><p>Designed at King’s College London, 2024–2026.</p></div></section>${footer()}`,'about')}

function bindHero(){const el=document.querySelector('#heroImage');if(!el)return;document.querySelector('.homeHero').onpointermove=e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX/r.width-.5)*8,y=(e.clientY/r.height-.5)*4;el.style.transform=`scale(1.025) translate(${x}px,${y}px)`};document.querySelector('.homeHero').onpointerleave=()=>el.style.transform='scale(1.025)'}
function bindArtistFilters(){const s=document.querySelector('#artistSearch'),m=document.querySelector('#movementFilter'),n=document.querySelector('#nationFilter'),g=document.querySelector('#artistGrid');const run=()=>{const q=s.value.toLowerCase();g.innerHTML=db.artists.filter(a=>(!q||(a.name+a.nameZh).toLowerCase().includes(q))&&(!m.value||a.movement===m.value)&&(!n.value||a.nationality===n.value)).map(artistCard).join('')};[s,m,n].forEach(x=>x.addEventListener('input',run));document.querySelector('#resetArtists').onclick=()=>{s.value=m.value=n.value='';run()}}
function bindWorkFilters(){const a=document.querySelector('#workArtist'),m=document.querySelector('#workMovement'),s=document.querySelector('#workSearch'),o=document.querySelector('#workSort'),g=document.querySelector('#worksGrid');const run=()=>{let rows=db.artworks.filter(w=>(!a.value||w.artistId===a.value)&&(!m.value||artist(w.artistId).movement===m.value)&&(!s.value||w.title.toLowerCase().includes(s.value.toLowerCase())));rows.sort((x,y)=>o.value==='latest'?(y.yearSort||0)-(x.yearSort||0):(x.yearSort||9999)-(y.yearSort||9999));g.innerHTML=rows.map(workCard).join('');document.querySelector('#workCount').textContent=rows.length};[a,m,s,o].forEach(x=>x.addEventListener('input',run))}
function route(){const[h='home',id]=location.hash.slice(1).split('/');if(h==='artists')artists();else if(h==='artist')artistDetail(id);else if(h==='works')works();else if(h==='work')workDetail(id);else if(h==='about')about();else home()}
addEventListener('hashchange',route);route();
